fix: add a check if file exists

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -22,8 +22,15 @@ jobs:
         uses: actions/checkout@v4
       - name: Check for uppercase letters in the dictionary
         run: |
-          echo "Looking for uppercase letters in dictionary.txt..."
-          if grep '[A-Z]' "static/dictionary.txt"; then
+          FILE_PATH="static/dictionary.csv"
+
+          if [ ! -f "$FILE_PATH" ]; then
+            echo "File not found: $FILE_PATH"
+            exit 1
+          fi
+
+          echo "Looking for uppercase letters in $FILE_PATH..."
+          if grep '[A-Z]' "$FILE_PATH"; then
             echo "Error: Uppercase letters found"
             exit 1
           else
@@ -32,6 +39,7 @@ jobs:
 
   bump-static-files-version:
     if: "!contains(github.event.head_commit.message, '[skip ci]')"
+    needs: checks
     runs-on: ubuntu-latest
     outputs:
       commit_sha: ${{ steps.push.outputs.commit_sha }}
